<?php
declare(strict_types=1);

namespace Tests\InitPHP\Translator\Unit;

use \InitPHP\Translator\Translator;

/**
 * This test is just to verify that indexed languages work correctly.
 * You can find some more extensive tests in the FileTranslatorTest class.
 */
class DirTranslatorTest extends \PHPUnit\Framework\TestCase
{
    protected Translator $lang;

    protected function setUp(): void
    {
        $this->lang = new Translator();
        $this->lang->useDirectory()
                ->setDir(__DIR__ . '/DirLanguages/')
                ->setDefault('en');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testEachLanguageIsADirectory()
    {

        $this->assertEquals('Hello World', $this->lang->_r('main.hello_world'));

        $this->lang->change('tr');

        $this->assertEquals('Merhaba Dünya', $this->lang->_r('main.hello_world'));

        $this->assertEquals('Yönetim Paneli', $this->lang->_r('admin.dashboard'));

        $this->lang->change('en');

        $this->assertEquals('Dashboard', $this->lang->_r('admin.dashboard'));

    }

}
